name: run reviewdog linters
on:
  pull_request:
    branch: main

jobs:
  set_envs:
    runs-on: ubuntu-latest
    outputs:
      reporter: ${{ steps.setenvs.outputs.reporter }}
    steps:
    - id: setenvs
      run: |
        if ${{ github.event_name == 'pull_request'}}; then
          echo "::set-output name=reporter::github-pr-review";
        else
          echo "::set-output name=reporter::github-check";
        fi
  action-cpplint:
    needs: set_envs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-cpplint@master
      with:
        github_token: ${{ secrets.github_token }}
        reporter: ${{ needs.set_envs.outputs.reporter }}
  action-hadolint:
    needs: set_envs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: reviewdog/action-hadolint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: ${{ needs.set_envs.outputs.reporter }}
